language: go
go:
  - 1.7
os:
  - linux
branches:
  only:
  - master
before_install:
  - go get -u github.com/kardianos/govendor
  - go get github.com/tools/godep
install:
  - make install 
deploy:
  provider: heroku
  api_key:
    secure: Qekv095+djtSGFkfObBLQMbrswaUUfPuPgxaI2zScpweNelaZg27SIIlOtK2B6IAVbfQw9k2IY1RnfAORR5z1WCdNtEC9AJ/30kPCfHYr9ajsSzRXcEuoQyPjDrmzMZByi4//WsbCuBdH7iQ3Bd+ak2Lg33800SCK7KLdmdhKCDgZlJh7krAwbrlPDK20wc8bzLDqqivyd5BeZuGaEm7zUtdfhXdD/cRnwPYCT03m9V5cxRkP9q3cV396U9TrVByOu9qIUgz7Y1vdgRPL4LqJb3ZWbgCUGKxofQWG/CxGqeM5V3LO+H4u9OqspljZab7Z2CF1hCtpO5Q4BMI5p0YHpIPPS3Bg1CcSC8otoPODQ0Xlvi72Tl46o9p34QpO5/RfYtju97L/ZjYRjHh+iFXom00RaYR2ZtFpF6/C3ocXlMnXOWxAPI85PIbk/SUlWkdDruL1YQhkyev+aY4LiLuwU2bjtfpbOIxUqqhm6Ftb3rkuseqOwAZ14X6GsPrVblaCZap0UmrTPLXB8M8FThpmj+Qb+9Q7KF3lqRqCqoTSOUSpP/PAHYxvrzALmb/EWbSFwG8Qvo06azB/eMlFXTkuE005es8wOZxRuMOJJOYCRwiVq03wgpTYS8nYb7HvkVJMwrqow3RMKjMW4Bp4P0Jo1VVibIXecwqxyYybP5aDUM=
  app: calm-lowlands-40938
  on:
    repo: 0xFranckx0/go-proxy-search
