language: go
go:
- 1.6
- 1.7
- 1.8
os:
- linux

# safelist
branches:
  only:
  - master

install:
- make deps
- make install

script:
- make test

deploy:
  provider: heroku
  api_key:
        secure: L6W/VpXLYDJp347+wmd9mbWGRbcMpH8Zc/l5Hio+w477a1uXFZ1wfrOeoC025ZCmbjkfgZru/xV8ArL4N+WjI1sXcwV6sBdFlr5CZ+qR578eL2AryZOpMCl0MPQNC4BM1Q+cYciOwo2NfFlX972+iQc+Xef/9iHc6cEJnTXAsG+vIZoeU+KFLJwVZyZmbk/d7q7KAGZNMi1D9FBC/1/JRrTEpJaRj2Z+ukSRDKDhL00UvEUAcuwuktXr99N5AvLW2mMIVX7hH4dU5Cx2F8i2b/zwAh2lbmYolpAXDzlwkhYUggqo2O5o5G2/PG5sb3Bsqof12Bzoj+XUb+SuemY6fRjfPYnVUDVrlSi2q452h1fYvI5SaX6l3jFhvLekTZdJ9ZnUOPo4SYGDASaFv9dx+YmiQlfilghxhFWu043rAzx6YSbDEODjchtVrLJia3Jww940S23W+U2lxZPaC2HM99+/AmYTYiBp88bE+2DjRBucy+wjgn0DNqUQdeaHQwF4NHh0QRp7PcS5utsPgUEPrfHQYSYGqkHYQPRYkpvvgytDFrd83S4MmAjCD1jwSq0/UmuhPhTn09patM9ewOqLONZvMyLGd38s7Ygv9al2gDmYq9dytoEvcelB28/MqSE0+WV29knot5sZZ5bFA4Jw9DKF9gsAUtywQiATmfgNUgE=
