language: go
go:
- 1.7
os:
- linux
branches:
  only:
  - master
install:
- make build
deploy:
  provider: heroku
  api_key:
    secure: dMNuYwW8LgBujjhT8MmYtHGeBlb+0NzSJOTOVXdiAtEg7lUHLEPeykDgIpvbxxYmYn0Q/HrWH3ZaCS7+IXRDaaqpu2VywfZb+p2myoAyNSava6FqJlyLAo2BIq2BU/HGzDYDoGJj5lH/euSHvVu5gWNcD19iIERehWUNvBJLUXPpb6DdWeMHnlD1KAqE23RaCR8In16UJMEvMGOFmvyjZowfksVvQdhlUDDXr6BsHHtOxDfryL8Vd4C0oRINdqArprF1d5W9HTKO1TIH4FhC5OW10gWXS/eg0Va6AJKC21yJGnWGOOYCe2AZWEXL0S9O5/b8az7TRCw2uTQpmN5T9hozfyc0MTp30OW4PzLlGdVAhit7eeeqWjMYaktdZtjwlPMNI9W53Pewp2BTigNyiwoB+1oDNg+YutmB9FewYWsnGKOBljsSqDKfIV4d+FrD1W3umE/5BYrQr6i49dPp3UYS9aHKzqnPmoQDU+rNMDbI79Oti2OI49gzh2KhcXisQhXF3lYJ+XK1ANCJ+uc7vgiiRX+YTKZWEgWKGvjZDh93d9XyNXp9xQnNeTe3ZMu2rCxOo3NPLJOm7dBpTZf60eWUwLnfXa5RvMPEhQFs50cHz6mSmMhSJc9T3io1mS/gyFd3C7PHiL/R8qKd1E4UA0Z01VFwfhuchEeE3eyWrcQ=
  app: radiant-brook-62510
  on:
    repo: 0xFranckx0/go-proxy-search
