language: go
go:
- 1.7
os:
- linux
branches:
  only:
  - master
install:
- make build
deploy:
  provider: heroku
  api_key:
    secure: HCTONKa+AZPySaKdXuMi3BtGwDfF5brd34Vhp+4+ho4x6UeWO9iVW/Wpm0IgpHw6NVYoivDXg9mG4DjB8xa9QmSpuV+mCC19iJOF/DxavzfIAzx6eoW6+bjlFxi2EOgrolxbNOKcNGP6yTZqeKAAFwbZixBKemMUPiT6AP8Cx474PMYWCQtmQQwjIxgJynFjD1bVZr1RKoP9HccEz2AQo6dH6b77AZsaWDMiDRhjuusMTflLP30EoxoJA3YSFw9kqBMUeEoYZLsiCHrZHamgQyIf19UVWqzJ1II2fn+9tx2irmLBFTNzqNORPFiDC8NfIa6fr7p6ShiaEeD0GFigEh3AlmffUpTiEkF9NCQ6NAeXSHIiqD3GBYAZiHJYRRAaZx9CbJjFdRXrQwUriqK86pxm2DQw5knGhCCFEgl/inyBw0KyamN+QjfKiD4tCjs7woBBnj5tXw6bDQWZHiLXhkJobY69CAJbFK2QGNbbceMYfUqjmw3Z7zuSb3O6HXyttSgJ25ozJkURqUpTpklTjER8ezRZic906GXdzUz0AVTC7VW6SwvyLUsarEu/9fZoXgIqHQUcaV43Z3hYqIeaECUhm7UZRFt0hGniso8iA3t8+tSP9nPlOn4wWe4T2jCHMriQ5G8v6P+Pg5Pmv1TaVQdSh+S8CqKzdeglo5dtyZo=
  app: radiant-brook-62510
  on:
    repo: 0xFranckx0/go-proxy-search
